@token = {{login.response.body.$.data.token}}

### 获取图形验证码
GET {{hostname}}/api/captcha

### 验证图形验证码
POST {{hostname}}/api/validate_captcha
Content-Type: application/json

{
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}


### 注册
# @name login
POST  {{hostname}}/api/regist
Content-Type: application/json

{
  "username": "18502087527",
  "password": "dev123456",
  "confirmPasswrod": "dewv123456",
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}

### 登录
# @name login
POST {{hostname}}/api/login
Content-Type: application/json

{
  "username": "18502087527",
  "password": "dev123456",
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}

### 商品列表
GET {{hostname}}/api/products

### 商品详情
{{hostname}}/api/products/13

### 添加商品
POST {{hostname}}/api/products
authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "面筋",
  "price": 1.5,
  "image": "https://picture.leigod.com/uploads/images/2025-09-12/1757672463492194.png",
  "count": 10,
  "categoryId": 1
}


### 编辑商品
POST {{hostname}}/api/products/13
authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 8,
  "count": 100
}

### 删除商品
DELETE  {{hostname}}/api/products/3
authorization: Bearer {{token}}


### 下单
POST {{hostname}}/api/orders
authorization: Bearer {{token}}

{
  "productIds": [2, 4]
}

### 订单列表
GET {{hostname}}/api/orders
authorization: Bearer {{token}}

### 地址列表
{{hostname}}/api/addresses
