@token = {{login.response.body.$.data.token}}
@token ={{admin_login.response.body.$.data.token}}}

### 全局配置查询
POST {{hostname}}/api/settings/list

{
  "keys": ["phone", "test", "test2"]
}

### 新建全局配置
POST {{hostname}}/api/settings

{
  "key": "test",
  "name": "联系电话",
  "value": {"type":1,"products":[1,2]}
}

### 更新全局配置

POST {{hostname}}/api/settings/1

{
  "key": "test2",
  "value": {"type":1111,"products":[1,2]}
}

### 管理员登录
# @name admin_login
POST {{hostname}}/api/admin_login

{
  "username": "18502087527",
  "password": "dev123456_DEV"
}

### 获取图形验证码
GET {{hostname}}/api/captcha

### 验证图形验证码
POST {{hostname}}/api/validate_captcha
Content-Type: application/json

{
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}


### 注册
# @name login
POST  {{hostname}}/api/regist
Content-Type: application/json

{
  "username": "18502087527",
  "password": "dev123456",
  "confirmPasswrod": "dewv123456",
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}

### 登录
# @name login
POST {{hostname}}/api/login
Content-Type: application/json

{
  "username": "18502087527",
  "password": "dev123456",
  "uuid": "877ddbbb-0199-4486-8770-bcd11cf4619c",
  "code": "1111"
}

### 商品列表
POST  {{hostname}}/api/products/list

### 商品详情
{{hostname}}/api/products/13

### 添加商品
POST {{hostname}}/api/products
authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "面筋",
  "price": 1.5,
  "image": "https://picture.leigod.com/uploads/images/2025-09-12/1757672463492194.png",
  "count": 10,
  "categoryId": 1
}


### 编辑商品
POST {{hostname}}/api/products/13
authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 8,
  "count": 100
}

### 删除商品
DELETE  {{hostname}}/api/products/3
authorization: Bearer {{token}}


### 下单
POST {{hostname}}/api/orders
authorization: Bearer {{token}}

{
  "productList": {
    "2": 2,
    "4": 5
  },
  "type": "pointPick",
  "dispatchTime": "2025-10-10 17:30:00",
  "remark": "中辣",
  "address": "7栋",
  "phone": 18502087527
}

### 查询订单 - 用户侧
Post {{hostname}}/api/orders/list
authorization: Bearer {{token}}

### 更改订单状态

POST {{hostname}}/api/orders/04e26dc3-ee2b-4f77-8cdc-3282293a038d/change_status
authorization: Bearer {{token}}

{
  "status": "material"
}